// <auto-generated/>
using System.Reflection;

[assembly: AssemblyVersionAttribute("3.4.3")]
[assembly: AssemblyFileVersionAttribute("0.3.2")]
[assembly: AssemblyInformationalVersionAttribute("0.3.2")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const string Version = "3.4.3";
        internal const string InformationalVersion = "0.3.2";
    }
}
